wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.40.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718286334
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      - 83
      - 98
      2:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      - 83
      - 98
      3:
      - 23
      - 24
      4: 3.12.3
      5: 0.17.0
      6: 4.40.2
      8:
      - 3
      - 5
      13: windows-amd64
pretrained_model_name_or_path:
  desc: null
  value: runwayml/stable-diffusion-v1-5
dataset_name:
  desc: null
  value: null
dataset_config_name:
  desc: null
  value: null
train_data_dir:
  desc: null
  value: dataset
image_column:
  desc: null
  value: image
caption_column:
  desc: null
  value: text
validation_prompt:
  desc: null
  value: '''Floor plan of a small apartment, few rooms, one bathroom, small kitchen,
    few windows'''
num_validation_images:
  desc: null
  value: 4
validation_epochs:
  desc: null
  value: 10
max_train_samples:
  desc: null
  value: null
output_dir:
  desc: null
  value: output_5
cache_dir:
  desc: null
  value: null
seed:
  desc: null
  value: 1337
resolution:
  desc: null
  value: 512
center_crop:
  desc: null
  value: false
random_flip:
  desc: null
  value: true
train_batch_size:
  desc: null
  value: 4
num_train_epochs:
  desc: null
  value: 215
max_train_steps:
  desc: null
  value: 15000
gradient_accumulation_steps:
  desc: null
  value: 1
gradient_checkpointing:
  desc: null
  value: false
learning_rate:
  desc: null
  value: 0.0001
scale_lr:
  desc: null
  value: false
lr_scheduler:
  desc: null
  value: cosine
lr_warmup_steps:
  desc: null
  value: 0
snr_gamma:
  desc: null
  value: null
use_8bit_adam:
  desc: null
  value: true
dataloader_num_workers:
  desc: null
  value: 0
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_weight_decay:
  desc: null
  value: 0.01
adam_epsilon:
  desc: null
  value: 1.0e-08
max_grad_norm:
  desc: null
  value: 1.0
prediction_type:
  desc: null
  value: null
logging_dir:
  desc: null
  value: logs
report_to:
  desc: null
  value: wandb
local_rank:
  desc: null
  value: -1
checkpointing_steps:
  desc: null
  value: 500
checkpoints_total_limit:
  desc: null
  value: null
resume_from_checkpoint:
  desc: null
  value: null
noise_offset:
  desc: null
  value: 0
rank:
  desc: null
  value: 4
